query getCategories {
  categories {
    data {
      id
      attributes {
        name
        subcategories {
          data {
            id
            attributes {
              name
              products {
                data {
                  id
                  attributes {
                    name
                    description
                    images {
                      data {
                        id
                        attributes {
                          name
                          formats
                          url
                          alternativeText
                        }
                      }
                    }
                    size
                    materials
                    price
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
