mutation createNewInvoice($invoice: InvoiceInput!) {
  createInvoice(data: $invoice) {
    data {
      id
      attributes {
        paid
        amount
        products {
          id
          quantity
          product_id
          product_name
        }
        payment_id
        order_id
        shipment_address
        createdAt
      }
    }
  }
}
