query GetInvoicesByUserId($id: ID) {
  invoices(filters: { users_permissions_user: { id: { eq: $id } } }) {
    data {
      id
      attributes {
        paid
        amount
        products {
          id
          quantity
          product_id
          product_name
        }
        payment_id
        order_id
        shipment_address
        createdAt
        payment_method
        payment_info {
          first_name
          last_name
          email
          amount
          confirmation_id
          payment_date
        }
      }
    }
  }
}
